# 会议配置文件
conferences:
  # 三大密码学会议
  crypto:
    - name: "CRYPTO"
      full_name: "International Cryptology Conference"
      dblp_key: "conf/crypto"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.iacr.org/archive/crypto{year}/crypto{year}.html"
      
  asiacrypt:
    - name: "ASIACRYPT"
      full_name: "International Conference on the Theory and Application of Cryptology and Information Security"
      dblp_key: "conf/asiacrypt"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.iacr.org/archive/asiacrypt{year}/asiacrypt{year}.html"
      
  eurocrypt:
    - name: "EUROCRYPT"
      full_name: "International Conference on the Theory and Applications of Cryptographic Techniques"
      dblp_key: "conf/eurocrypt"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.iacr.org/archive/eurocrypt{year}/eurocrypt{year}.html"
  
  # Big 4 安全会议
  usenix_security:
    - name: "USENIX Security"
      full_name: "USENIX Security Symposium"
      dblp_key: "conf/uss"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.usenix.org/conference/usenixsecurity{year}/technical-sessions"
      
  sp:
    - name: "IEEE S&P"
      full_name: "IEEE Symposium on Security and Privacy"
      dblp_key: "conf/sp"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.ieee-security.org/TC/SP{year}/program-papers.html"
      
  ccs:
    - name: "CCS"
      full_name: "ACM Conference on Computer and Communications Security"
      dblp_key: "conf/ccs"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.sigsac.org/ccs/{year}/program.html"
      
  ndss:
    - name: "NDSS"
      full_name: "Network and Distributed System Security Symposium"
      dblp_key: "conf/ndss"
      years: [2020, 2021, 2022, 2023, 2024]
      url_template: "https://www.ndss-symposium.org/{year}/accepted-papers/"
